### PR TITLE
Update graceful-fs. Closes #17

### LINKED ISSUE #17: Bump graceful-fs dependency
`graceful-fs` versions lower than v4 reevaluate native `fs` module source, which is not supported.
You should update your `graceful-fs` dependency to v4 or later. 

Tracking issue: https://github.com/nodejs/node/issues/5213.

### PR DESCRIPTION
**Pull request by peterblazejewicz**
See: 
https://github.com/nodejs/node/issues/5213

### CODE REVIEW

**Comment by jkrot** [comment]
Could someone approve this please.  Trying to get all the graceful-fs errors out of my builds.

**Comment by jkrot** [comment]
@peterblazejewicz  Can you bump https://www.npmjs.com/package/temp-write  as well because that uses graceful-fs@2.0.3 in the current version which will still have the build errors.

**Comment by JoostvdB94** [comment]
Also fixed by #20

**Comment by jkrot** [comment]
Would love for this to get merged.

**Comment by chilijung** [comment]
https://github.com/chilijung/gulp-cssmin/pull/20

**Pull request closed without merging**
